#!/usr/bin/env python3
"""Single source of truth for the two symptom-group tables in the report:

  * bang:rules    -- "Nhóm triệu chứng và cụm từ tiếng Việt dùng để khớp"
  * bang:findings -- "Tần suất các nhóm triệu chứng trong lớp Bất thường"

Both tables share ONE taxonomy defined here (group name -> raw rule labels +
representative Vietnamese phrases), so they stay consistent by construction.
Frequencies are counted from Script/labels.xlsx: for every ABNORMAL study we
collect the SET of groups its conclusion matches (a study may belong to several
groups), counted once each, split into X-ray-only and all modalities.

Usage:
    python Script/build_findings_table.py            # both LaTeX table bodies
    python Script/build_findings_table.py --rules    # only bang:rules body
    python Script/build_findings_table.py --findings # only bang:findings body
"""
import argparse
import csv
from collections import Counter

import dicom_labeler as D  # AORTA/ABNORMAL patterns + text normalization

# (display name, {raw pattern labels}, "representative Vietnamese phrases")
# Raw labels come from dicom_labeler.ABNORMAL_CONTAINS_PATTERNS plus "aorta".
GROUPS = [
    ("Cung động mạch chủ vồng/vôi hóa", {"aorta"},
     "``quai/cung động mạch chủ'' kèm ``vồng''; ``quai động mạch chủ vôi hóa''"),
    ("Đám mờ/khối mờ", {"opacity/mass shadow"},
     "``mờ''; ``đám mờ''"),
    ("Xơ hóa/xẹp phổi/giãn phế quản", {"fibrosis/atelectasis/bronchiectasis"},
     "``xơ''; ``xẹp''; ``giãn phế quản''"),
    ("Tràn dịch màng phổi", {"pleural effusion"},
     "``tràn dịch''"),
    ("Bất thường phế quản", {"bronchial/peribronchial abnormality"},
     "``phế quản''; ``dày thành phế quản''; ``tăng đậm các nhánh phế huyết quản''"),
    ("Bất thường bóng tim", {"enlarged heart"},
     "``bóng tim to''; ``tim to''; ``tim bè''; ``bè thất trái''"),
    ("Tổn thương/nốt/u/hang/lao", {"lesion", "solid nodule/tumor/cavity/tuberculosis"},
     "``tổn thương''; ``nốt đặc''; ``u thùy''; ``u phổi''; ``hang phổi''; ``lao''"),
    ("Gãy xương/vỡ lún", {"fracture", "compression fracture"},
     "``gãy''; ``vỡ lún''"),
    ("Dày tổ chức kẽ", {"interstitial thickening"},
     "``dày tổ chức kẽ''; ``dày kẽ''"),
    ("Dày/dính màng phổi", {"pleural thickening/adhesion"},
     "``dày dính màng phổi''; ``dày màng phổi''"),
    ("Viêm", {"inflammation"},
     "``viêm''"),
    ("Khí phế thũng/kén khí", {"emphysema/air cyst"},
     "``khí phế thũng''; ``kén khí''"),
    ("Tràn khí màng phổi", {"pneumothorax"},
     "``tràn khí''"),
    ("Các nhóm khác", {
        "catheter", "blunted costophrenic angle", "hemorrhage",
        "sinus mucosal thickening/fluid", "node/mediastinum",
        "prominent left hilum", "calcified dense nodule", "soft tissue edema",
    },
     "``góc sườn hoành tù''; ``hạch/rộng trung thất''; ``xuất huyết''; "
     "``phù nề''; ``catheter''; ``rốn phổi trái đậm''; ``nốt đậm vôi''; ``ứ dịch xoang''"),
]

NORMAL_PHRASES = ("``không thấy bất thường''; ``hai phổi bình thường''; "
                  "``trường phổi hai bên sáng đều''; kết luận rỗng")


def matched_groups(conclusion: str) -> set:
    t = D.normalize_text(D.extract_conclusion(conclusion)).rstrip(" .:-")
    raw = set()
    if ("vong" in t and any(a in t for a in D.AORTA_CONTAINS_PATTERNS)) \
            or ("voi hoa" in t and "quai dong mach chu" in t) \
            or ("quai dong mach chu voi hoa" in t):
        raw.add("aorta")
    for label, terms in D.ABNORMAL_CONTAINS_PATTERNS:
        if any(term in t for term in terms):
            raw.add(label)
    return {name for name, labels, _ in GROUPS if raw & labels}


def count(labels_path):
    xray, allc = Counter(), Counter()
    for r in D.read_csv(labels_path):  # accepts labels.xlsx or .csv
        if r.get("coarse_label") != "ABNORMAL":
            continue
        is_xray = (r.get("modality") == "X-ray")
        for g in matched_groups(r.get("conclusion", "")):
            allc[g] += 1
            if is_xray:
                xray[g] += 1
    return xray, allc


def rules_body():
    print("% bang:rules -- auto-generated by Script/build_findings_table.py")
    print(f"    Bình thường & {NORMAL_PHRASES} \\\\")
    print("    \\midrule")
    for name, _, phrases in GROUPS:
        disp = name + (" (nhóm hiếm)" if name == "Các nhóm khác" else "")
        print(f"    {disp} & {phrases} \\\\")


def findings_body(labels_path):
    xray, allc = count(labels_path)
    print("% bang:findings -- auto-generated by Script/build_findings_table.py")
    tx = ta = 0
    for name, _, _ in GROUPS:
        disp = name + (" (mỗi nhóm $\\leq 5$)" if name == "Các nhóm khác" else "")
        print(f"    {disp} & {xray[name]} & {allc[name]} \\\\")
        tx += xray[name]
        ta += allc[name]
    print("    \\midrule")
    print(f"    \\bfseries Tổng lượt nhóm triệu chứng & \\bfseries {tx} & \\bfseries {ta} \\\\")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--labels", default="Script/labels.xlsx")
    ap.add_argument("--rules", action="store_true")
    ap.add_argument("--findings", action="store_true")
    args = ap.parse_args()
    both = not (args.rules or args.findings)
    if args.rules or both:
        rules_body()
        print()
    if args.findings or both:
        findings_body(args.labels)


if __name__ == "__main__":
    main()
